config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new form create destroy]
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[new create] do
          end
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      can :read, :all
    elsif user.role == 'admin'
      can :manage, :all
    else
      can %i[read create], :all
      can %i[update destroy], :all, { Author_id: user.id }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'authorId'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_create :update_counter
  after_destroy :comment_decrement

  def update_counter
    post.increment!(:CommentsCounter)
  end

  def comment_decrement
    post.decrement!(:CommentsCounter)
  end
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist
  self.table_name = 'jwt_denylist'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'AuthorId'
  belongs_to :post, class_name: 'Post', foreign_key: 'PostId'

  after_save :update_counter

  def update_counter
    post.increment!(:LikesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :Title, presence: true, length: { maximum: 250 }
  # validates :LikesCounter, numericality: { only_integer: true,
  # greater_than_or_equal_to: 0 }
  # validates :CommentsCounter, numericality: { only_integer: true,
  # greater_than_or_equal_to: 0 }

  belongs_to :user, class_name: 'User', foreign_key: 'authorId'
  has_many :comments, class_name: 'Comment', foreign_key: 'PostId'
  has_many :likes, class_name: 'Like', foreign_key: 'PostId'

  after_create :update_counter

  def update_counter
    user.increment!(:PostCounter)
  end

  def recent_comment
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  validates :Name, presence: true
  validates :PostCounter, Numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, class_name: 'Post', foreign_key: 'authorId'
  has_many :comments, class_name: 'Comment', foreign_key: 'authorId'
  has_many :likes, class_name: 'Like', foreign_key: 'authorId'

  def recent_post
    posts
  end

  def all_posts
    posts.order(created_at: :desc)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    comment = Comment.find(params[:id])
    render json: comment
  end

  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.new(comment_params)
    render json: comment, status: 'Created' if comment.save
  end

  private

  def comment_params
    params.require(:comment).permit(:Text, :author_id, :post_id)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    render json: @posts
  end

  def show
    @post = Post.find(params[:id])
    render json: @post
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
       %i[email name password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save
      flash[:success] = 'New Comment created successfully'
      redirect_to user_posts_path(current_user, @post)
    else
      flash.now[:error] = 'An error occurred : Comment could not be created'
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    @status_update = Comment.find(params[:id])
    @status_update.destroy if @status_update.present?
    redirect_to user_post_path(post.user.id, post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:Text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.create
    @like.user = current_user
    @like.post = @post
    if @like.save
      flash[:success] = 'Like Added successfully'
      redirect_to user_posts_path(current_user, @post)
    else
      flash.now[:error] = 'An Error occurred: Like could not be saved'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find_by(params[:authorId])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'New Post created successfully'
          redirect_to user_posts_path(current_user)
        else
          flash.now[:error] = 'An error occurred : Post could not be created'
        end
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    # flash[:notice] = ['Comment Deleted Successfully']
    redirect_to user_post_path(current_user, params[:post_id]), notice: 'Successfully removed the comment.'
  end

  private

  def post_params
    params.require(:post).permit(:Title, :Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_comment.html.erb
<% if post.CommentsCounter > 0 %>
  <% post.recent_comment.each do |comment| %>
    <p><%= comment.user.Name %> : <%= comment.Text%></p>
  <% end %>
<% else %>
  <p>No comments!</p>
<% end %>

app/views/partials/_form.html.erb
<div >
  <%= form_with model: Comment, url: post_comments_path(@post.user, @post), method: :post do |form| %>
    <%= form.text_field :text, placeholder: 'Your comment here...' %>
    <%= form.submit "Add a comment" %>
  <% end %>
</div>

app/views/partials/_post.html.erb
<h1><%= post.id%> </h1>
<h3><%= post.Title%> </h3>
<%= post.Text %>
<p >Comments: <span><%= post.CommentsCounter %></span>, 
Likes: <span><%= post.LikesCounter %></span></p>

<% if can? :destroy, post %>
     <%= button_to "Destroy this post", user_post_path(@user.id, post.id), method: :delete %>
<% end %>

app/views/partials/_post_helper.html.erb
 <h2><%= post.Title%> </h2>
    <% if post.Text.length > 110 %>
      <%= truncate(post.text, length: 110) ... %>
    <% else %>
      <%= post.Text %>.
    <% end %>
  </p>
  <p>Comments: <span><%= post.CommentsCounter %></span>, Likes: <span><%= post.LikesCounter %></span></p>
</div>

app/views/partials/_user.html.erb
<div>
    <img src=<%= user.Photo %> alt= '<%= user.Name %>' class="img-fluid rounded mx-auto d-block"/>
</div>
<div>
    <h2><%= user.Name %></h2>
    <p>Number of posts: <%= user.PostCounter %></p>
</div>

app/views/posts/form.html.erb
<div>
  <h1>Create a Post </h1>
  <%= form_with model: Post, method: :post do |form| %>
    <%= form.label :Title %>
    <%= form.text_field :Title, placeholder: 'Post title ...' %><br />
    <%= form.label :Text, "Post" %>
    <%= form.text_area :Text, placeholder: 'Post here...' %><br />
    <%= form.submit "Post Now" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= render partial: 'partials/post', locals: {post: post} %>
    <%= render partial: 'partials/comment', locals: {post: post} %>
<% end %>
<a >Pagination</a>

app/views/posts/show.html.erb
<p><%= @post.Title %> by <%= @post.user.Name%></p>
<p>Comments: <span><%= @post.CommetCounter %></span>, Likes: <span><%= @post.LikesCounter %></span></p>

<%= @post.text %>
    <%= form_with model: Like, url: post_likes_path(@post.user, @post), method: :post do |form| %>
    <% form.submit "Like" %>
<% end %>
<% if @post.comments.length > 0 %>
    <% @post.comments.each do |comment| %>
    <p><%= comment.user.Name %> : <%= comment.Text %></p>
<% end %>
    <% else %>
    <p>There are no comments !!</p>
<% end %>

<% if can? :destroy, comment %>
    <%= button_to "Destroy this comment", post_comment_path(post.id, comment.id), method: :delete %>
<% end %>

<div>
    <h3>Add a comment</h3>
    <%= render partial: 'partials/_new' %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>

  <%= link_to user, id: user.id do %>
  <%= render partial: 'partials/user', locals: {user: user} %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div>
    <%= render partial: 'partials/user', locals: {user: @user} %>
    <p>Bio: <%= @user.Bio %> </p>
    <% if @user.PostCounter < 0 %> 
        <p><%= @user.Name %> doesn't have a post !></p>
    <% else %>
        <% @user.recent_post.each do |post| %>
            <%= render partial: 'partials/post_helper', locals: {post: post} %>
        <% end %>   
         <%= link_to("See all posts", user_posts_path(@user))  %> 
    <% end %>
</div>